---
title: "Project "
---

Enormous basketball player dataset
```{r}
setwd("~/Documents/Data Analysis")
data = read.csv("players_stats_by_season_full_details.csv")

```

```{r}
data = data[, !names(data) %in% c("birth_month", "height", "weight", "high_school")]
#Gets Rid of Useless Columns
library(NbClust)
library(expss)
library(leaps)
#Adds libraries I will be needing
```


```{r}
data$FGP = (data$FGM / data$FGA)
data$X3PP = (data$X3PM / data$X3PA)
data$FTP = (data$FTM / data$FTA)
#Turns Field Goals, Free Throws, and 3 Point Shots Attempts and Makes into a Percentage

data$PPM = data$PTS / data$MIN
data$APM = data$AST / data$MIN
data$RPM = data$REB / data$MIN
data$SPM = data$STL / data$MIN
data$BPM = data$BLK / data$MIN
#Converts Points, Assists, Rebounds, Steals, and Blocks into a function of how many of each stat / minute. This removes bias from playing time, and
#will be helpful in Problem 2, where playing time can skew data

data$humanAssignedCluster = rep(0,nrow(data))
data$guard = rep(0,nrow(data))
data$guard[data$height_cm <= 193] = 1
data$big = rep(0,nrow(data))
data$big[data$height_cm >= 208] = 1
data$wing = rep(0,nrow(data))
data$wing[(!data$big)&(!data$guard)] = 1
data$humanAssignedCluster[data$big == 1] = 3
data$humanAssignedCluster[data$guard == 1] = 2
data$humanAssignedCluster[data$wing == 1] = 1
#In This section of data frame modifications, I assigned each player a score based on height. A player has been designated a Guard if they are 193cm or
#shorter (6'4"). A player has been designated a Big if they are 208cm or taller (6'10"). If a player is neither a Guard nor a Big, they are called a 
#Wing- anywhere from 194cm-207cm (6'5" - 6'9"). This obviously is a naive approach to assigning positions to players, as exceptions like Ben Simmons (a
#6'10 Guard, Kevin Durant (a 6'10 Wing), Draymond Green (a 6'6 Big) come to mind.

data$season = as.character(substr(data$Season, 1, 4))
#This adds an additional column to the dataset that is the numeric value of what year the season starts.
nba = data[data$League == "NBA", ]
#This creates a new dataset where only NBA statistics are included

```


Number 1- What determines points scored in each league
```{r}
eurocup = data[data$League == "Eurocup", ]
euroleague = data[data$League == "Euroleague", ]
spanishACB = data[data$League == "Spanish-ACB", ]
AustralianNBL = data[data$League == "Australian-NBL", ]
#Like NBA above, these lines of code seperate out the next 4 leagues with the most data entries

australian_best_model = regsubsets(data = AustralianNBL, PTS ~ AST + REB + BLK + TOV + STL + FGP + FTP + height_cm + draft_pick)
australian_reg_model = lm(data = AustralianNBL, PTS ~ REB + TOV + STL + FTP )
#Best Determining characteristics of PTS in Australian NBL is REb, TOV, STL, FTP


eurocup_best_model = regsubsets(data = eurocup, PTS ~ AST + REB + BLK + TOV + STL + FGP + FTP + height_cm + draft_pick)
eurocup_reg_model = lm(data = eurocup, PTS ~ REB + TOV + STL + FGP + FTP + height_cm)
#Best determining characteristics of PTS in Eurocup is Reb, TOV, STL, FGP, FTP, height


euroleaguebest_model = regsubsets(data = euroleague, PTS ~ AST + REB + BLK + TOV + STL + FGP + FTP + height_cm + draft_pick)
euroleague_reg_model = lm(data = euroleague, PTS ~ REB + TOV + STL + FGP + FTP + height_cm)
#best characteristics of PTS in Euroleague is Reb, TOV, STL, FGP, FTP, height


nba_bestt_model = regsubsets(data = nba, PTS ~ AST + REB + BLK + TOV + STL + FGP + FTP + height_cm + draft_pick)
nba_reg_model = lm(data = nba, PTS ~ AST + REB + TOV + STL + FTP)
#Best characteristics of PTS in NBA is Ast, Reb, TOV, Stl, FTP


spanishACB_best_model = regsubsets(data = spanishACB, PTS ~ AST + REB + BLK + TOV + STL + FGP + FTP + height_cm + draft_pick)
spanish_reg_model = lm(data = spanishACB, PTS ~ REB + TOV + STL + FGP + FTP)
#Best characteristics of PTS in spanishACB is Reb, TOV, STL, FGP, FTP


```


Number 2 -Clustering stats by position-
```{r}
#Step 0- Scaling and Splitting the data
nba = na.omit(nba)
set.seed(2)
#We exclude NA values from these calculations

nba.std = (nba[,31:38])
nba.std = data.frame(scale(nba.std))
#Create a new DataFrame of scaled data

kmeans_3 = kmeans((nba.std), centers = 3)
table(kmeans_3$cluster)
aggregate(nba[,31:38], by = list(kmeans_3$cluster), median)
pairs(nba.std[,4:8], col = as.factor(kmeans_3$cluster))
#Creates a 3 Cluster breakdown of how the computer groups together players based on statistics per minute. This is similar to the height-assigned 
#values from above.

#In the graph, Black represents Cluster 1- Wings. Red represents Cluster 2- Guards. Green represents Cluster 3- Bigs.
nba$computerCluster = kmeans_3$cluster
#Assigns each of their computer-assigned positions (clusters) to the original dataset
cross_cases(nba, nba$humanAssignedCluster, nba$computerCluster)
#Compares how many players both the Computer and I put into the same category. Roughly 65% Success in Naive approach.
```





Number 3A- Average stats by league with 1 year blocks
```{r}
#aggregate straight
cnums = c(10,14,15,18,19,20,21,22)
nba_reg_szn = nba[nba$Stage == "Regular_Season",]
avgGameNum = mean(nba_reg_szn$GP)
statsByYear = data.frame(aggregate(nba_reg_szn[,cnums], by = list(nba_reg_szn$season), mean))
#This Creates a new data frame where only Regular Season NBA games are valued. Each statistic from cnums is averaged over a yearly basis.

statsByYear$personal_X3pm = statsByYear$X3PM / avgGameNum
statsByYear$personal_TOV = statsByYear$TOV / avgGameNum
statsByYear$personal_PF = statsByYear$PF / avgGameNum
statsByYear$personal_REB = statsByYear$REB / avgGameNum
statsByYear$personal_AST = statsByYear$AST / avgGameNum
statsByYear$personal_STL = statsByYear$STL / avgGameNum
statsByYear$personal_BLK = statsByYear$BLK / avgGameNum
statsByYear$personal_PTS = statsByYear$PTS / avgGameNum
#Converts Average Yearly Statistics for Players into Stats/Game, by using the Average number of games played.
#Data frame is now set up.
```


Number 3B- Actual Graphs
```{r}
pts = barplot(statsByYear$personal_PTS, names.arg = statsByYear$Group.1,main = "Average PTS / Game over Last 21 Seasons", col = "green", ylim = c(0,16), xlab = "Year", ylab = "Points")
text(pts, y = statsByYear$personal_PTS, label = trunc(statsByYear$personal_PTS * 10)/10, pos = 3, cex = .75, col = "black")
#Plotting Points / Year

reb = barplot(statsByYear$personal_REB, names.arg = statsByYear$Group.1,main = "Average Rebounds / Game over Last 21 Seasons", col = "chocolate1", xlab = "Year", ylab = "Rebounds", ylim = c(0,7))
text(reb, y = statsByYear$personal_REB, label = trunc(statsByYear$personal_REB * 10)/10, pos = 3, cex = .75, col = "black")
#Plotting Rebounds / Year

ast = barplot(statsByYear$personal_AST, names.arg = statsByYear$Group.1,main = "Average Assists / Game over Last 21 Seasons", col = "gold", xlab = "Year", ylab = "Assists", ylim = c(0,4))
text(ast, y = statsByYear$personal_AST, label = trunc(statsByYear$personal_AST * 10)/10, pos = 3, cex = .75, col = "black")
#Plotting Assists / Year

threes = barplot(statsByYear$personal_X3pm, names.arg = statsByYear$Group.1,main = "Average 3 Pointers Made / Game over Last 21 Seasons", col = "firebrick", xlab = "Year", ylab = "3 Pointers Made", ylim = c(0,1.5))
text(threes, y = statsByYear$personal_X3pm, label = trunc(statsByYear$personal_X3pm * 10^2)/10^2, pos = 3, cex = .75, col = "black")
#Plotting 3 Pointers made / Year


stl = barplot(statsByYear$personal_STL, names.arg = statsByYear$Group.1,main = "Average Steals / Game over Last 21 Seasons", col = "darkorchid", xlab = "Year", ylab = "Steals", ylim = c(0,1.25))
text(stl, y = statsByYear$personal_STL, label = trunc(statsByYear$personal_STL * 10^2)/10^2, pos = 3, cex = .75, col = "black")
#Plotting Steals / Year

blk = barplot(statsByYear$personal_BLK, names.arg = statsByYear$Group.1,main = "Average Blocks / Game over Last 21 Seasons", col = "blue", ylim = c(0,.8), xlab = "Year", ylab = "Blocks")
text(blk, y = statsByYear$personal_BLK, label = trunc(statsByYear$personal_BLK * 10^2)/10^2, pos = 3, cex = .75, col = "black")
#Plotting Blocks / Year

```


